# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e37d4c6c51acca161b295c41a7b4ac00ae0c5959a547dd7a56805757e924523ebfffbdf1731aeeeefbb477e5ce63b64e209d5bfdabf19b1d017502d5600986a

test:
  secret_key_base: aa40cad60895938883f6f14db83dc31b1f70040c95dd8fa3ffe6eb6adb19e3d92aea4efb8a717b1d354fcb3ea356eb74be31d10df48db496f14e1b519bd3f274

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
